[project]
name = "cap-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.7",
    "opencv-contrib-python>=4.12.0.88",
    "pandas>=2.3.3",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.231",
]
