# The following yaml is based on the coco8.yaml  data configuration setinggs template

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: data # dataset root dir
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images

nc: 3

# Classes
names:
  0: light blue
  1: dark blue
  2: other
