# Model & Training
logging:
  project: bottle_cap_detection
  run_name: train_b8_ep500_im320

train:
  model: yolo11n.pt
  data: configs/data.yaml
  epochs: 100
  batch: 8
  imgsz: 320
  lr0: 0.001
  optimizer: AdamW

# Augmentation (critical for small data)
aug:
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 10.0
  translate: 0.1
  scale: 0.5
  shear: 2.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1
  mixup: 0.1

# Inference
infer:
  model_path: bottle_cap_detection/train_b8_ep500_im320/weights/best.pt
  project: "bottle_cap_detection/train_b8_ep500_im320/"
  name: predictions
  conf: 0.5
  iou: 0.45