name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-screen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Enable caching
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: formatting check with Black
        run: uv run black --check .

      - name: sorting check isort
        run: uv run isort --check . -v

      - name: linter check pylint
        run: uv run pylint bsort

      - name: pytest
        run: uv run pytest

  docker-build:
      needs: code-screen
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: df -h  
        - run: docker build -t bsort:latest . --no-cache 



